export const routes = {
  home: '/',
  services: '/services',
  service: (slug: string) => `/services/${slug}`,
  solutions: '/solutions',
  solution: (slug: string) => `/solutions/${slug}`,
  industries: '/industries',
  industry: (slug: string) => `/industries/${slug}`,
  about: '/about',
  trust: '/trust',
  caseStudies: '/case-studies',
  resources: '/insights',
  resource: (slug: string) => `/insights/${slug}`,
  careers: '/careers',
  contact: '/contact',
  assessment: '/request-assessment',
  incident: '/incident-response',
  disclosure: '/report-vulnerability',
  privacy: '/legal/privacy',
  terms: '/legal/terms',
  cookies: '/legal/cookies',
  responsibleDisclosure: '/legal/responsible-disclosure',
  login: '/portal/login',
  portal: '/portal',
  admin: '/admin',
} as const;
